name: PyTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django djangorestframework pytest pytest-django


    - name: Run migrations
      env:
        DJANGO_SETTINGS_MODULE: skoumal_task.settings
      run: python manage.py migrate

    - name: Run tests with pytest
      run: pytest -v
